# Air Wick Freshmatic cap for battery cover (smart home automation)
# https://www.thingiverse.com/thing:5060683

substitutions:
  device_name: bad-air-wick-freshmatic
  device_friendly_name: Bad Air Wick Freshmatic
  device_area: Bad

esphome:
  name: ${device_name}
  friendly_name: ${device_friendly_name}
  area: ${device_area}
  project:
    name: "AWF1877.D1_mini_plus_switchable_battery"
    version: "0.0"

esp8266:
  board: d1_mini

packages:
  wifi: !include common/wifi.yaml
  general: !include common/general.yaml

status_led:
  pin:
    number: D4
    inverted: true

switch:
  - platform: gpio
    name: Stromversorgung
    id: air_wick_power_enabled
    pin: D5
    icon: mdi:electric-switch-closed
