
# esphome -s scale_id 01 run bienenstockwaage.yaml
# esphome -s scale_id 02 run bienenstockwaage.yaml
# esphome -s scale_id 03 run bienenstockwaage.yaml
# esphome -s scale_id 04 run bienenstockwaage.yaml
# esphome -s scale_id 05 run bienenstockwaage.yaml
# esphome -s scale_id 06 run bienenstockwaage.yaml
# esphome -s scale_id 07 run bienenstockwaage.yaml
# esphome -s scale_id test run bienenstockwaage.yaml

# esphome -s scale_id 01 run --device 192.168.23.41 bienenstockwaage.yaml

  
# Bienenstockwaage
#
# Beispielhafte Umrechnungsformel: weight = 0.00004194443 * raw + 6.318476
# Wenn sich das Gewicht stark ändert (z.B. beim Kalibrieren) dauert es bis der Wert völlig stabil ist.
#   Nach 15 Minuten: Circa 15 Gramm vom unmittelbaren Messwert
#   Nach 60 Minuten: Circa 22 Gramm vom unmittelbaren Messwert, stabil
# Erfahrungswert: Konvertierter Messwert (ohne Filter) schwankt mit Standardabweichung von circa 0,002 kg


substitutions:
  scale_id: "00"

  device_name: bienenstockwaage-${scale_id}
  device_friendly_name: Bienenstockwaage ${scale_id}
  device_area: Garten

  # Referenz-Gewichte auf Dachboden
  refweight_0kg: "0.0"
  refweight_30kg: "30.0"
  refweight_78_5kg: "78.5"  # 30.0 + 48.5

  scale_test_refweight_0kg_raw:    "-3410881" # Nicht gemessen, nur angenähert! Muss noch ermittelt werden.
  scale_test_refweight_30kg_raw:     "351850"
  scale_test_refweight_78_5kg_raw:  "1472100"
  #
  scale_01_refweight_0kg_raw:        "684598" # Nicht gemessen, nur angenähert! Muss noch ermittelt werden.
  scale_01_refweight_30kg_raw:      "1378000"
  scale_01_refweight_78_5kg_raw:    "2499000"
  #
  scale_02_refweight_0kg_raw:       "-353088"
  scale_02_refweight_30kg_raw:       "362451"
  scale_02_refweight_78_5kg_raw:    "1526746"
  #
  scale_03_refweight_0kg_raw:       "-150316"
  scale_03_refweight_30kg_raw:       "564070"
  scale_03_refweight_78_5kg_raw:    "1721084"
  #
  scale_04_refweight_0kg_raw:        "-33351" # Nicht gemessen, nur angenähert! Muss noch ermittelt werden.
  scale_04_refweight_30kg_raw:       "599000"
  scale_04_refweight_78_5kg_raw:    "1621300"
  #
  scale_05_refweight_0kg_raw:       "-174921"
  scale_05_refweight_30kg_raw:       "510290"
  scale_05_refweight_78_5kg_raw:    "1624466"
  #
  scale_06_refweight_0kg_raw:        "359521" # Nicht gemessen, nur angenähert! Muss noch ermittelt werden.
  scale_06_refweight_30kg_raw:      "1081500"
  scale_06_refweight_78_5kg_raw:    "2248700"
  #
  scale_07_refweight_0kg_raw:        "284244"
  scale_07_refweight_30kg_raw:       "974875"
  scale_07_refweight_78_5kg_raw:    "2098076"

esphome:
  name: ${device_name}
  friendly_name: ${device_friendly_name}
  area: ${device_area}
  project:
    name: "AWF1877.D1_mini_plus_HX711_load_cells"
    version: "0.0"

esp8266:
  board: d1_mini

packages:
  wifi: !include common/wifi.yaml
  general: !include common/general.yaml

# wifi: { use_address: 192.168.23.45 }  # Better: esphome run --device 192.168.23.45 bienenstockwaage.yaml

# https://esphome.io/components/sensor/hx711.html
sensor:
  - platform: hx711
    id: hx711_raw_value
    name: HX711 raw value
    dout_pin: D1
    clk_pin: D2
    update_interval: 1s
    internal: true

  # Nur für Kalibrierung!
  # Um unnötige Speicherbelastung zu vermeiden im Produktivbetrieb deaktivieren.
  # - platform: copy
  #   source_id: hx711_raw_value
  #   name: HX711 raw value (average)
  #   filters:
  #     - sliding_window_moving_average:
  #         window_size: 30
  #         send_every: 30
  #   accuracy_decimals: 0
  #   internal: true

  - platform: copy
    source_id: hx711_raw_value
    name: Gewicht
    filters:
      - median:
          window_size: 3
          send_every: 3
          send_first_at: 3
      - calibrate_linear:
          datapoints:
          - from: ${scale_${scale_id}_refweight_0kg_raw}
            to: ${refweight_0kg}
          - from: ${scale_${scale_id}_refweight_30kg_raw}
            to: ${refweight_30kg}
          - from: ${scale_${scale_id}_refweight_78_5kg_raw}
            to: ${refweight_78_5kg}
      - or:
        - delta: 0.02
        - heartbeat: 30min
    accuracy_decimals: 2
    icon: mdi:scale
    device_class: weight
    unit_of_measurement: kg
