# esphome -s device_name epaper-display-oben -s device_friendly_name "ePaper Display oben" -s device_area "kitchen" run epaper-display.yaml
# esphome -s device_name epaper-display-unten -s device_friendly_name "ePaper Display unten" -s device_area "Untere Etage" run epaper-display.yaml

substitutions:
  device_name: epaper-display-default
  device_friendly_name: ePaper Display Default
  device_area: default

  status_led_pin: GPIO27

# Project based on https://github.com/maxmacstn/HA-ePaper-Display

esphome:
  name: ${device_name}
  friendly_name: ${device_friendly_name}
  area: ${device_area}
  platform: esp32
  board: pico32

  on_boot:
    - priority: -10
      then:
        - delay: 15s
        - component.update: epaperdisplay

# TRY THIS
# logger:
#   level: DEBUG
#   hardware_uart: USB_SERIAL_JTAG

packages:
  wifi: !include common/wifi.yaml
  general: !include common/general.yaml
  status_led: !include include/on_board_status_led_sk6812.yaml
  include_1: !include include/epaper_display_fonts.yaml
  include_2: !include include/epaper_display_homeassistant.yaml
  include_3: !include include/epaper_display_screen.yaml

# wifi:
#   use_address: 192.168.23.187

sensor:
  - platform: template
    name: "Last Content Update"
    device_class: timestamp
    id: epaperdisplay_last_update

button:
  - platform: template
    name: "Force Cotent Update"
    icon: mdi:calendar-refresh
    on_press:
      - component.update: epaperdisplay
