# esphome -s device_name epaper-display-oben -s device_friendly_name "ePaper Display oben" run epaper-display.yaml
# esphome -s device_name epaper-display-unten -s device_friendly_name "ePaper Display unten" run epaper-display.yaml

substitutions:
  device_name: epaper-display-default
  device_friendly_name: ePaper Display Default

# Project based on https://github.com/maxmacstn/HA-ePaper-Display

esphome:
  name: ${device_name}
  friendly_name: ${device_friendly_name}
  platform: esp32
  board: pico32

  on_boot:
    priority: -10
    then:
      - delay: 15s
      - component.update: epaperdisplay

packages:
  wifi: !include common/wifi.yaml
  general: !include common/general.yaml
  include_1: !include include/epaper_display_fonts.yaml
  include_2: !include include/epaper_display_homeassistant.yaml
  include_3: !include include/epaper_display_screen.yaml

# wifi:
#   use_address: 192.168.23.204

sensor:
  - platform: template
    name: "Last Content Update"
    device_class: timestamp
    id: epaperdisplay_last_update
