substitutions:
  device_name: gartenbewaesserung-astra
  device_friendly_name: Gartenbewaesserung Astra
  device_area: Garten

  buzzer_pin: GPIO12
  blue_led_pin: GPIO4

# https://rocketcontroller.com/yaml-configuration-esphome-home-assistant-for-esp32r4-controller/
# https://rocketcontroller.com/documentation-astra-configuration-esphome-home-assistant-for-astra-module/

# ASTRA BR4G8AL
# https://rocketcontroller.com/product/astra-controller-4-relays-16a-8-gpio-input-dc-power-led-br4g8al/

esphome:
  name: ${device_name}
  friendly_name: ${device_friendly_name}
  area: ${device_area}
  project:
    name: "ASTRA.BR4G8AL"
    version: "0.0"

esp32:
  board: esp32dev
  framework:
    type: arduino

packages:
  wifi: !include common/wifi.yaml
  general: !include common/general.yaml
  include_rtttl: !include include/buzzer_rtttl.yaml
  include_1: !include include/gartenbewaesserung_valves.yaml
  include_2: !include include/gartenbewaesserung_sensors.yaml
  include_3: !include include/gartenbewaesserung_controller.yaml
  include_4: !include include/gartenbewaesserung_controller_boot.yaml
  include_5: !include include/gartenbewaesserung_controller_extra.yaml

# wifi: { use_address: 192.168.23.x }

################################################################################

logger:
  logs:
    # By default, every reading will be printed to the UART, which is very slow
    # This will disable printing the readings but keep other helpful messages
    sensor: INFO

status_led:
  pin:
    number: ${blue_led_pin}
    inverted: true

###############################################################################

i2c:
  id: i2c_component
  sda: 13
  scl: 14
  scan: true
  frequency: 50kHz
