substitutions:
  device_name: haus-uv
  device_friendly_name: Haus UV
  device_area: Flur

  buzzer_pin: GPIO12

  circuit_01: DG (21B)
  circuit_02: OG Neubau Beleuchtung (22C)
  circuit_03: OG Altbau (ausser gr. Kinderzimmer) (23A)
  circuit_04: OG Gr. Kinderzimmer (24B)
  circuit_05: OG Bad Steckdosen (25A)
  circuit_06: OG Neubau Steckdosen (außer Bad) (26B)
  circuit_07: UG Kueche Herd L1 (37A)
  circuit_08: UG Kueche Herd L2 (38B)
  circuit_09: UG Kueche Herd L3 (39C)
  circuit_10: KG Neubau Steckdosen (ausser Heizung und Netzwerk) (40A)
  circuit_11: UG Neubau Steckdosen (ausser Bad und Vorbau) (41B)
  circuit_12: UG Neubau Beleuchtung, Vorbau Steckdosen (42C)
  circuit_13: UG Bad Steckdosen (43A)
  circuit_14: KG Neubau Heizung und Netzwerk (44B)
  circuit_15: KG Neubau Beleuchtung (45C)
  circuit_16: UG Altbau (46A)
  group_total: Total
  group_balance: Unbemessene Sicherungen (17A, 18B, 19C, 20A, 27, 33A, 34B, 35C, 47B, 48)
  group_herd: UG Kueche Herd (37A, 38B, 39C)
  group_dg: DG Total
  group_og: OG Total
  group_ug: UG Total
  group_kg: KG Total


# https://github.com/emporia-vue-local/esphome

esphome:
  name: ${device_name}
  friendly_name: ${device_friendly_name}
  area: ${device_area}

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    version: recommended

packages:
  wifi: !include common/wifi.yaml
  general: !include common/general.yaml
  include_rtttl: !include include/buzzer_rtttl.yaml

# wifi:
#   use_address: 192.168.23.193  # manual IP overwrite

################################################################################

external_components:
  - source: github://emporia-vue-local/esphome@dev
    components:
      - emporia_vue

logger:
  logs:
    # By default, every reading will be printed to the UART, which is very slow
    # This will disable printing the readings but keep other helpful messages
    sensor: INFO

preferences:
  # please also make sure `restore: false` is set on all `platform: total_daily_energy`
  # sensors below.
  flash_write_interval: "48h"

output:
  - platform: gpio
    pin: GPIO27
    id: buzzer_gnd
    # Pin pulled to GND for proper function of buzzer

light:
  - platform: status_led
    name: "D3_LED"
    pin: 23
    restore_mode: ALWAYS_ON
    entity_category: config
    internal: true

i2c:
  sda: 21
  scl: 22
  scan: false
  frequency: 200kHz  # recommended range is 50-200kHz
  id: i2c_a

# needed for total_daily_energy
time:
  - platform: sntp
    id: time_sntp
    timezone: Europe/Berlin

# these are called references in YAML. They allow you to reuse
# this configuration in each sensor, while only defining it once
.defaultfilters:
  - &throttle_avg
    # average all raw readings together over a 5 second span before publishing
    throttle_average: 5s
  - &throttle_time
    # only send the most recent measurement every 60 seconds
    throttle: 60s
  - &invert
    # invert and filter out any values below 0.
    lambda: 'return max(-x, 0.0f);'
  - &pos
    # filter out any values below 0.
    lambda: 'return max(x, 0.0f);'
  - &abs
    # take the absolute value of the value
    lambda: 'return abs(x);'
  - &wh_to_kwh
    # Convert to kWh
    multiply: 0.001

sensor:
  - platform: emporia_vue
    i2c_id: i2c_a
    phases:
      - id: phase_a  # Verify that this specific phase/leg is connected to correct input wire color on device listed below
        input: BLACK  # Vue device wire color
        calibration: 0.0232  # 0.022 is used as the default as starting point but may need adjusted to ensure accuracy
        # To calculate new calibration value use the formula <in-use calibration value> * <accurate voltage> / <reporting voltage>
        voltage:
          name: "L1 Spannung"
          filters: [*throttle_avg, *pos]
        frequency:
          name: "L1 Frequenz"
          filters: [*throttle_avg, *pos]
      - id: phase_b  # Verify that this specific phase/leg is connected to correct input wire color on device listed below
        input: RED  # Vue device wire color
        calibration: 0.02227  # 0.022 is used as the default as starting point but may need adjusted to ensure accuracy
        # To calculate new calibration value use the formula <in-use calibration value> * <accurate voltage> / <reporting voltage>
        voltage:
          name: "L2 Spannung"
          filters: [*throttle_avg, *pos]
        phase_angle:
          name: "L2 Phasenwinkel"
          filters: [*throttle_avg, *pos]
      - id: phase_c  # Verify that this specific phase/leg is connected to correct input wire color on device listed below
        input: BLUE  # Vue device wire color
        calibration: 0.02149  # 0.022 is used as the default as starting point but may need adjusted to ensure accuracy
        # To calculate new calibration value use the formula <in-use calibration value> * <accurate voltage> / <reporting voltage>
        voltage:
          name: "L3 Spannung"
          filters: [*throttle_avg, *pos]
        phase_angle:
          name: "L3 Phasenwinkel"
          filters: [*throttle_avg, *pos]
    ct_clamps:
      # Do not specify a name for any of the power sensors here, only an id. This leaves the power sensors internal to ESPHome.
      # Copy sensors will filter and then send power measurements to HA
      # These non-throttled power sensors are used for accurately calculating energy
      - phase_id: phase_a
        input: "A"  # Verify the CT going to this device input also matches the phase/leg
        power:
          id: phase_a_power
          filters: [*pos]
      - phase_id: phase_b
        input: "B"  # Verify the CT going to this device input also matches the phase/leg
        power:
          id: phase_b_power
          filters: [*pos]
      - phase_id: phase_c
        input: "C"  # Verify the CT going to this device input also matches the phase/leg
        power:
          id: phase_c_power
          filters: [*pos]
      # Pay close attention to set the phase_id for each breaker by matching it to the phase/leg it connects to in the panel
      - { phase_id: phase_b, input:  "1", power: { id:  cir1, filters: [ *pos ] } }
      - { phase_id: phase_c, input:  "2", power: { id:  cir2, filters: [ *pos ] } }
      - { phase_id: phase_a, input:  "3", power: { id:  cir3, filters: [ *pos ] } }
      - { phase_id: phase_b, input:  "4", power: { id:  cir4, filters: [ *pos ] } }
      - { phase_id: phase_a, input:  "5", power: { id:  cir5, filters: [ *pos ] } }
      - { phase_id: phase_b, input:  "6", power: { id:  cir6, filters: [ *pos ] } }
      - { phase_id: phase_a, input:  "7", power: { id:  cir7, filters: [ *pos ] } }
      - { phase_id: phase_b, input:  "8", power: { id:  cir8, filters: [ *pos ] } }
      - { phase_id: phase_c, input:  "9", power: { id:  cir9, filters: [ *pos ] } }
      - { phase_id: phase_a, input: "10", power: { id: cir10, filters: [ *pos ] } }
      - { phase_id: phase_b, input: "11", power: { id: cir11, filters: [ *pos ] } }
      - { phase_id: phase_c, input: "12", power: { id: cir12, filters: [ *pos ] } }
      - { phase_id: phase_a, input: "13", power: { id: cir13, filters: [ *pos ] } }
      - { phase_id: phase_b, input: "14", power: { id: cir14, filters: [ *pos ] } }
      - { phase_id: phase_c, input: "15", power: { id: cir15, filters: [ *pos ] } }
      - { phase_id: phase_a, input: "16", power: { id: cir16, filters: [ *pos ] } }
    on_update:
      then:
        - component.update: total_power
        - component.update: balance_power
        - component.update: ug_kueche_herd_power
        - component.update: dg_sum_power
        - component.update: og_sum_power
        - component.update: ug_sum_power
        - component.update: kg_sum_power

  - platform: template
    lambda: return id(phase_a_power).state + id(phase_b_power).state + id(phase_c_power).state;
    update_interval: never   # will be updated after all power sensors update via on_update trigger
    id: total_power
    device_class: power
    state_class: measurement
    unit_of_measurement: "W"

  - platform: template
    lambda: !lambda |-
      return max(0.0f, id(total_power).state -
        id( cir1).state -
        id( cir2).state -
        id( cir3).state -
        id( cir4).state -
        id( cir5).state -
        id( cir6).state -
        id( cir7).state -
        id( cir8).state -
        id( cir9).state -
        id(cir10).state -
        id(cir11).state -
        id(cir12).state -
        id(cir13).state -
        id(cir14).state -
        id(cir15).state -
        id(cir16).state);
    update_interval: never   # will be updated after all power sensors update via on_update trigger
    id: balance_power
    device_class: power
    state_class: measurement
    unit_of_measurement: "W"

  # The copy sensors filter and send the power state to HA
  - { platform: copy, source_id: phase_a_power, name: "L1 Power", filters: *throttle_avg }
  - { platform: copy, source_id: phase_b_power, name: "L2 Power", filters: *throttle_avg }
  - { platform: copy, source_id: phase_c_power, name: "L3 Power", filters: *throttle_avg }

  - { platform: copy, source_id: total_power, name: "${group_total} Power", filters: *throttle_avg }
  - { platform: copy, source_id: balance_power, name: "${group_balance} Power", filters: *throttle_avg }

  - { platform: copy, source_id:  cir1, name: "${circuit_01} Power", filters: *throttle_avg }
  - { platform: copy, source_id:  cir2, name: "${circuit_02} Power", filters: *throttle_avg }
  - { platform: copy, source_id:  cir3, name: "${circuit_03} Power", filters: *throttle_avg }
  - { platform: copy, source_id:  cir4, name: "${circuit_04} Power", filters: *throttle_avg }
  - { platform: copy, source_id:  cir5, name: "${circuit_05} Power", filters: *throttle_avg }
  - { platform: copy, source_id:  cir6, name: "${circuit_06} Power", filters: *throttle_avg }
# - { platform: copy, source_id:  cir7, name: "${circuit_07} Power", filters: *throttle_avg }
# - { platform: copy, source_id:  cir8, name: "${circuit_08} Power", filters: *throttle_avg }
# - { platform: copy, source_id:  cir9, name: "${circuit_09} Power", filters: *throttle_avg }
  - { platform: copy, source_id: cir10, name: "${circuit_10} Power", filters: *throttle_avg }
  - { platform: copy, source_id: cir11, name: "${circuit_11} Power", filters: *throttle_avg }
  - { platform: copy, source_id: cir12, name: "${circuit_12} Power", filters: *throttle_avg }
  - { platform: copy, source_id: cir13, name: "${circuit_13} Power", filters: *throttle_avg }
  - { platform: copy, source_id: cir14, name: "${circuit_14} Power", filters: *throttle_avg }
  - { platform: copy, source_id: cir15, name: "${circuit_15} Power", filters: *throttle_avg }
  - { platform: copy, source_id: cir16, name: "${circuit_16} Power", filters: *throttle_avg }

  # Daily energy

  - { platform: total_daily_energy, power_id: total_power, name: "${group_total} Energy Daily", unit_of_measurement: 'kWh', accuracy_decimals: 3, restore: false, filters: [*throttle_time, *wh_to_kwh] }
  - { platform: total_daily_energy, power_id: balance_power, name: "${group_balance} Energy Daily", unit_of_measurement: 'kWh', accuracy_decimals: 3, restore: false, filters: [*throttle_time, *wh_to_kwh] }

  - { platform: total_daily_energy, power_id:  cir1, name: "${circuit_01} Energy Daily", unit_of_measurement: 'kWh', accuracy_decimals: 3, restore: false, filters: [*throttle_time, *wh_to_kwh] }
  - { platform: total_daily_energy, power_id:  cir2, name: "${circuit_02} Energy Daily", unit_of_measurement: 'kWh', accuracy_decimals: 3, restore: false, filters: [*throttle_time, *wh_to_kwh] }
  - { platform: total_daily_energy, power_id:  cir3, name: "${circuit_03} Energy Daily", unit_of_measurement: 'kWh', accuracy_decimals: 3, restore: false, filters: [*throttle_time, *wh_to_kwh] }
  - { platform: total_daily_energy, power_id:  cir4, name: "${circuit_04} Energy Daily", unit_of_measurement: 'kWh', accuracy_decimals: 3, restore: false, filters: [*throttle_time, *wh_to_kwh] }
  - { platform: total_daily_energy, power_id:  cir5, name: "${circuit_05} Energy Daily", unit_of_measurement: 'kWh', accuracy_decimals: 3, restore: false, filters: [*throttle_time, *wh_to_kwh] }
  - { platform: total_daily_energy, power_id:  cir6, name: "${circuit_06} Energy Daily", unit_of_measurement: 'kWh', accuracy_decimals: 3, restore: false, filters: [*throttle_time, *wh_to_kwh] }
# - { platform: total_daily_energy, power_id:  cir7, name: "${circuit_07} Energy Daily", unit_of_measurement: 'kWh', accuracy_decimals: 3, restore: false, filters: [*throttle_time, *wh_to_kwh] }
# - { platform: total_daily_energy, power_id:  cir8, name: "${circuit_08} Energy Daily", unit_of_measurement: 'kWh', accuracy_decimals: 3, restore: false, filters: [*throttle_time, *wh_to_kwh] }
# - { platform: total_daily_energy, power_id:  cir9, name: "${circuit_09} Energy Daily", unit_of_measurement: 'kWh', accuracy_decimals: 3, restore: false, filters: [*throttle_time, *wh_to_kwh] }
  - { platform: total_daily_energy, power_id: cir10, name: "${circuit_10} Energy Daily", unit_of_measurement: 'kWh', accuracy_decimals: 3, restore: false, filters: [*throttle_time, *wh_to_kwh] }
  - { platform: total_daily_energy, power_id: cir11, name: "${circuit_11} Energy Daily", unit_of_measurement: 'kWh', accuracy_decimals: 3, restore: false, filters: [*throttle_time, *wh_to_kwh] }
  - { platform: total_daily_energy, power_id: cir12, name: "${circuit_12} Energy Daily", unit_of_measurement: 'kWh', accuracy_decimals: 3, restore: false, filters: [*throttle_time, *wh_to_kwh] }
  - { platform: total_daily_energy, power_id: cir13, name: "${circuit_13} Energy Daily", unit_of_measurement: 'kWh', accuracy_decimals: 3, restore: false, filters: [*throttle_time, *wh_to_kwh] }
  - { platform: total_daily_energy, power_id: cir14, name: "${circuit_14} Energy Daily", unit_of_measurement: 'kWh', accuracy_decimals: 3, restore: false, filters: [*throttle_time, *wh_to_kwh] }
  - { platform: total_daily_energy, power_id: cir15, name: "${circuit_15} Energy Daily", unit_of_measurement: 'kWh', accuracy_decimals: 3, restore: false, filters: [*throttle_time, *wh_to_kwh] }
  - { platform: total_daily_energy, power_id: cir16, name: "${circuit_16} Energy Daily", unit_of_measurement: 'kWh', accuracy_decimals: 3, restore: false, filters: [*throttle_time, *wh_to_kwh] }

  # Additional sensors

  - platform: template
    id: ug_kueche_herd_power
    lambda: !lambda |-
      return max(0.0f, id(cir7).state + id(cir8).state + id(cir9).state);
    update_interval: never   # will be updated after all power sensors update via on_update trigger
    device_class: power
    state_class: measurement
    unit_of_measurement: "W"
  - { platform: copy, name: "${group_herd} Power", source_id: ug_kueche_herd_power, filters: *throttle_avg }
  - { platform: total_daily_energy, power_id: ug_kueche_herd_power, name: "${group_herd} Energy Daily", unit_of_measurement: 'kWh', accuracy_decimals: 3, restore: false, filters: [*throttle_time, *wh_to_kwh] }

  - platform: template
    id: dg_sum_power
    lambda: !lambda |-
      return max(0.0f, id(cir1).state);
    update_interval: never   # will be updated after all power sensors update via on_update trigger
    device_class: power
    state_class: measurement
    unit_of_measurement: "W"
  - { platform: copy, name: "${group_dg} Power", source_id: dg_sum_power, filters: *throttle_avg }
  - { platform: total_daily_energy, power_id: dg_sum_power, name: "${group_dg} Energy Daily", unit_of_measurement: 'kWh', accuracy_decimals: 3, restore: false, filters: [*throttle_time, *wh_to_kwh] }

  - platform: template
    id: og_sum_power
    lambda: !lambda |-
      return max(0.0f, id(cir2).state + id(cir3).state + id(cir4).state + id(cir5).state + id(cir6).state);
    update_interval: never   # will be updated after all power sensors update via on_update trigger
    device_class: power
    state_class: measurement
    unit_of_measurement: "W"
  - { platform: copy, name: "${group_og} Power", source_id: og_sum_power, filters: *throttle_avg }
  - { platform: total_daily_energy, power_id: og_sum_power, name: "${group_og} Energy Daily", unit_of_measurement: 'kWh', accuracy_decimals: 3, restore: false, filters: [*throttle_time, *wh_to_kwh] }

  - platform: template
    id: ug_sum_power
    lambda: !lambda |-
      return max(0.0f, id(cir7).state + id(cir8).state + id(cir9).state + id(cir11).state + id(cir12).state + id(cir13).state + id(cir16).state);
    update_interval: never   # will be updated after all power sensors update via on_update trigger
    device_class: power
    state_class: measurement
    unit_of_measurement: "W"
  - { platform: copy, name: "${group_ug} Power", source_id: ug_sum_power, filters: *throttle_avg }
  - { platform: total_daily_energy, power_id: ug_sum_power, name: "${group_ug} Energy Daily", unit_of_measurement: 'kWh', accuracy_decimals: 3, restore: false, filters: [*throttle_time, *wh_to_kwh] }

  - platform: template
    id: kg_sum_power
    lambda: !lambda |-
      return max(0.0f, id(cir10).state + id(cir14).state + id(cir15).state);
    update_interval: never   # will be updated after all power sensors update via on_update trigger
    device_class: power
    state_class: measurement
    unit_of_measurement: "W"
  - { platform: copy, name: "${group_kg} Power", source_id: kg_sum_power, filters: *throttle_avg }
  - { platform: total_daily_energy, power_id: kg_sum_power, name: "${group_kg} Energy Daily", unit_of_measurement: 'kWh', accuracy_decimals: 3, restore: false, filters: [*throttle_time, *wh_to_kwh] }
