substitutions:
  device_name: haus-uv-astra
  device_friendly_name: Haus UV Astra
  device_area: Flur

  rtttl_out_pin: GPIO12
  blue_led_pin: GPIO4

# https://rocketcontroller.com/yaml-configuration-esphome-home-assistant-for-esp32r4-controller/
# https://rocketcontroller.com/documentation-astra-configuration-esphome-home-assistant-for-astra-module/

# ASTRA BR4G8AL
# https://rocketcontroller.com/product/astra-controller-4-relays-16a-8-gpio-input-dc-power-led-br4g8al/

esphome:
  name: ${device_name}
  friendly_name: ${device_friendly_name}
  area: ${device_area}
  project:
    name: "AWF1877.ASTRA_BR4G8AL"
    version: "0.0"

esp32:
  board: esp32dev
  framework:
    type: arduino

packages:
  wifi: !include common/wifi.yaml
  general: !include common/general.yaml
  include_1: !include include/haus_uv_astra_relays.yaml
  include_2: !include include/haus_uv_astra_klingel.yaml
  include_3: !include include/haus_uv_astra_nachtlicht.yaml
  include_4: !include include/rtttl_out.yaml

# wifi:
#   use_address: 192.168.23.33

################################################################################

logger:
  logs:
    # By default, every reading will be printed to the UART, which is very slow
    # This will disable printing the readings but keep other helpful messages
    sensor: INFO

status_led:
  pin:
    number: ${blue_led_pin}
    inverted: true
