substitutions:
  device_name: heizungsregelung
  device_friendly_name: Heizungsregelung
  device_area: Keller

# AZ-Delivery ESP-32 Dev Kit C V4
# https://www.az-delivery.de/en/products/esp-32-dev-kit-c-v4
# https://cdn.shopify.com/s/files/1/1509/1638/files/ESP-32_DevKit_C_V4_Datenblatt_AZ-Delivery_Vertriebs_GmbH_24ec770f-c65e-4bd3-92c9-cd64b4d070b8.pdf?v=1615364587
# https://cdn.shopify.com/s/files/1/1509/1638/files/ESP32_DevKit_C_V4_Pinout.pdf?v=1615364529
# https://docs.platformio.org/en/latest/boards/espressif32/az-delivery-devkit-v4.html
# https://randomnerdtutorials.com/esp32-pinout-reference-gpios/
esphome:
  name: ${device_name}
  comment: ${device_friendly_name}
  friendly_name: ${device_friendly_name}
  area: ${device_area}

esp32:
  board: az-delivery-devkit-v4
  framework:
    type: arduino

time:
  - platform: sntp
    id: time_sntp
    timezone: Europe/Berlin

packages:
  wifi: !include common/wifi.yaml
  general: !include common/general.yaml
  include_01: !include include/heizungsregelung_i2c_enclosure.yaml
  include_02: !include include/heizungsregelung_relais.yaml
  include_03: !include include/heizungsregelung_em10_pwm.yaml
  include_04: !include include/heizungsregelung_temp_pt1000_spi.yaml
  include_05: !include include/heizungsregelung_temp_ds18b20_gpio32.yaml
  include_06: !include include/heizungsregelung_temp_ds18b20_gpio33.yaml
  include_07: !include include/heizungsregelung_temp_diff.yaml
  include_08: !include include/heizungsregelung_energy_heat_counter.yaml
  include_09: !include include/heizungsregelung_energy_heat_flow.yaml
  include_10: !include include/heizungsregelung_energy_solar_production.yaml
  include_11: !include include/heizungsregelung_energy_electric.yaml

# wifi: { use_address: 192.168.23.x }

# https://esphome.io/components/status_led.html
status_led:
  pin: GPIO19  # Rote LED

output:
  # LEDs in Frontblende
  # https://esphome.io/components/output/gpio.html
  - id: green_led_output
    platform: gpio
    pin: GPIO23
  #- id: red_led_output
  #  platform: gpio
  #  pin: GPIO19

light:
  # https://esphome.io/components/light/binary.html
  # https://esphome.io/components/light/index.html
  - platform: binary
    name: Abdeckung Status-LED gruen
    output: green_led_output
    restore_mode: ALWAYS_OFF

#binary_sensor:
#  - platform: gpio
#    name: Gastherme Stoermeldung
#    pin:
#      number: GPIO25
#      mode: INPUT_PULLUP
#      inverted: false
#    device_class: problem
#    filters:
#      - delayed_on: 100ms
#      - delayed_off: 100ms
#  - platform: gpio
#    name: Wassereinbruch Alarm
#    pin:
#      number: GPIO26
#      mode: INPUT_PULLUP
#      inverted: false
#    device_class: problem
#    filters:
#      - delayed_on: 100ms
#      - delayed_off: 100ms


# # https://esphome.io/components/debug.html
# debug:
#   #update_interval: 5s
# sensor:
#   - platform: debug
#     free:
#       name: Heap Free
#       id: heap_free
#     block:
#       name: Heap Max Block
#       id: heap_max_block
#     loop_time:
#       name: Loop Time
#       id: loop_time

#   - platform: template
#     name: Heap Free (relative)
#     id: heap_free_percent
#     unit_of_measurement: '%'
#     accuracy_decimals: 1
#     icon: mdi:percent
#     # update_interval: 5s
#     entity_category: diagnostic
#     # 524288 B (SRAM total)
#     # 327680 B (DRAM usable)
#     lambda: return ( id(heap_free).state * 100 / 327680 );

#   - platform: template
#     name: Heap Max Block (relative)
#     id: heap_max_block_percent
#     unit_of_measurement: '%'
#     accuracy_decimals: 1
#     icon: mdi:percent
#     # update_interval: 5s
#     entity_category: diagnostic
#     # 524288 B (SRAM total)
#     # 327680 B (DRAM usable)
#     lambda: return ( id(heap_max_block).state * 100 / 327680 );

# # https://esphome.io/components/runtime_stats/
# # This component is intended for debugging and troubleshooting
# runtime_stats:
#   log_interval: 60s