substitutions:
  device_name: raumsensorknoten
  device_friendly_name: Raumsensorknoten
  device_area: Kinderzimmer

  rtttl_out_pin: GPIO4
  status_led_pin: GPIO2


esphome:
  name: ${device_name}
  friendly_name: ${device_friendly_name}
  area: ${device_area}
  project:
    name: "AWF1877.Raumsensorknoten_ESP32-C3-SuperMini"
    version: "0.0"

packages:
  system: !include system/stamp_c3u.yaml
  wifi: !include common/wifi.yaml
  general: !include common/general.yaml
  status_led: !include include/on_board_status_led_sk6812.yaml
  include_rtttl: !include include/rtttl_out.yaml

# wifi:
#   use_address: 192.168.23.126

i2c:
  id: i2c_component
  sda: GPIO6
  scl: GPIO7
  scan: true
  frequency: 50kHz

mcp23017:
  - id: mcp23017_expander
    address: 0x20

output:
  - id: buzzer_out
    platform: gpio
    pin: GPIO3

switch:
  - platform: output
    name: "Buzzer"
    output: buzzer_out

  - platform: gpio
    name: "MCP23017 Pin A6 Out G"
    pin:
      mcp23xxx: mcp23017_expander
      number: 6
      mode:
        output: true
      inverted: false

  - platform: gpio
    name: "MCP23017 Pin A7 Out Y"
    pin:
      mcp23xxx: mcp23017_expander
      number: 7
      mode:
        output: true
      inverted: false

sensor:
  - platform: bme280_i2c
    temperature:
      name: "BME280 Temperature"
      oversampling: 16x
    pressure:
      name: "BME280 Pressure"
    humidity:
      name: "BME280 Humidity"
    address: 0x76
    update_interval: 10s

  - platform: bme680
    temperature:
      name: "BME680 Temperature"
      oversampling: 16x
    pressure:
      name: "BME680 Pressure"
    humidity:
      name: "BME680 Humidity"
    gas_resistance:
      name: "BME680 Gas Resistance"
    address: 0x77
    update_interval: 10s

  - platform: sht3xd
    temperature:
      name: "SHT31 Temperature"
    humidity:
      name: "SHT31 Humidity"
    address: 0x44
    update_interval: 60s

  - platform: aht10
    id: aht21_sensor
    variant: AHT20
    update_interval: 10s
    address: 0x38
    temperature:
      name: "AHT21 Temperature"
      id: aht21_temp
    humidity:
      name: "AHT21 Humidity"
      id: aht21_humi

  - platform: ens160
    id: ens160_sensor
    address: 0x53
    update_interval: 10s
    eco2:
      name: "ENS160 eCO2"
      id: ens160_eco2
    tvoc:
      name: "ENS160 Total Volatile Organic Compounds"
      id: ens160_tvoc
    aqi:
      name: "ENS160 Air Quality Index"
      id: ens160_aqi
    compensation:
      temperature: aht21_temp
      humidity: aht21_humi

  - platform: adc
    name: "Water Pressure Sensor"
    id: water_pressure_adc
    pin: GPIO0
    update_interval: 3s
    accuracy_decimals: 3
    attenuation: auto
    #update_interval: 20ms
    internal: false
    #filters:


binary_sensor:
  - platform: gpio
    name: "On-board Button"
    internal: false
    pin:
      number: GPIO9
      inverted: true
    filters:
      - delayed_on: 50ms
    # on_press:
    #   then:
    #     ...

  - platform: gpio
    name: "MCP23017 Pin A5 In"
    pin:
      mcp23xxx: mcp23017_expander
      number: 5
      mode:
        input: true
        pullup: true
      inverted: true


# MCP23017 Configuration
#
# VCC - Not needed for this project
# GND - Physically extended to 10 connectors: 5x LED common and Pushbutton common
#
# # Power button
# PB7 (15) - LED0 Button input (pull-up)
# PB6 (14) - LED0 R (only button where we use the red channel, due to multiplexer size)
# PB5 (13) - LED0 G
# PB4 (12) - LED0 Y
# # Valve 1 button
# PB3 (11) - LED1 Button input (pull-up)
# PB2 (10) - LED1 G
# PB1 (09) - LED1 Y
# # Valve 2 button
# PB0 (08) - LED2 Button input (pull-up)
# PA0 (00) - LED2 G
# PA1 (01) - LED2 Y
# # Valve 3 button
# PA2 (02) - LED3 Button input (pull-up)
# PA3 (03) - LED3 G
# PA4 (04) - LED3 Y
# # Valve 4 button
# PA5 (05) - LED4 Button input (pull-up)
# PA6 (06) - LED4 G
# PA7 (07) - LED4 Y
