substitutions:
  device_name: raumsensorknoten
  device_friendly_name: Raumsensorknoten
  device_area: Kinderzimmer

  buzzer_pin: GPIO4
  status_led_pin: GPIO2


esphome:
  name: ${device_name}
  friendly_name: ${device_friendly_name}
  area: ${device_area}
  project:
    name: "AWF1877.Raumsensorknoten_ESP32-C3-SuperMini"
    version: "0.0"

packages:
  system: !include system/stamp_c3u.yaml
  wifi: !include common/wifi.yaml
  general: !include common/general.yaml
  status_led: !include include/on_board_status_led_sk6812.yaml
  include_rtttl: !include include/buzzer_rtttl.yaml

# wifi:
#   use_address: 192.168.23.126


i2c:
  id: i2c_component
  sda: GPIO6
  scl: GPIO7
  scan: true
  frequency: 50kHz


output:
  - id: buzzer_out
    platform: gpio
    pin: GPIO3


switch:
  - platform: output
    name: "Buzzer"
    output: buzzer_out


sensor:
  - platform: bme280_i2c
    temperature:
      name: "BME280 Temperature"
      oversampling: 16x
    pressure:
      name: "BME280 Pressure"
    humidity:
      name: "BME280 Humidity"
    address: 0x76
    update_interval: 10s

  - platform: bme680
    temperature:
      name: "BME680 Temperature"
      oversampling: 16x
    pressure:
      name: "BME680 Pressure"
    humidity:
      name: "BME680 Humidity"
    gas_resistance:
      name: "BME680 Gas Resistance"
    address: 0x77
    update_interval: 10s

  - platform: sht3xd
    temperature:
      name: "SHT31 Temperature"
    humidity:
      name: "SHT31 Humidity"
    address: 0x44
    update_interval: 60s

  - platform: aht10
    id: aht21_sensor
    variant: AHT20
    update_interval: 10s
    address: 0x38
    temperature:
      name: "AHT21 Temperature"
      id: aht21_temp
    humidity:
      name: "AHT21 Humidity"
      id: aht21_humi

  - platform: ens160
    id: ens160_sensor
    address: 0x53
    update_interval: 10s
    eco2:
      name: "ENS160 eCO2"
      id: ens160_eco2
    tvoc:
      name: "ENS160 Total Volatile Organic Compounds"
      id: ens160_tvoc
    aqi:
      name: "ENS160 Air Quality Index"
      id: ens160_aqi
    compensation:
      temperature: aht21_temp
      humidity: aht21_humi


binary_sensor:
  - platform: gpio
    name: "On-board Button"
    internal: false
    pin:
      number: GPIO9
      inverted: true
    filters:
      - delayed_on: 50ms
    # on_press:
    #   then:
    #     ...
