substitutions:
  device_name: torfahrtsschuppen-raumsensor
  device_friendly_name: Torfahrtsschuppen Raumsensor
  device_area: Torfahrtsschuppen

  status_led_pin: GPIO8
  on_board_button_pin: GPIO9

  buzzer_pin: GPIO4


esphome:
  name: ${device_name}
  friendly_name: ${device_friendly_name}
  area: ${device_area}

packages:
  system: !include system/esp32_c3_supermini.yaml
  wifi: !include common/wifi.yaml
  general: !include common/general.yaml
  status_led: !include include/on_board_status_led_single.yaml
  include_rtttl: !include include/buzzer_rtttl.yaml

# wifi:
#   use_address: 192.168.23.172


i2c:
  id: i2c_component
  sda: GPIO2
  scl: GPIO3
  scan: true
  frequency: 50kHz


sensor:
  # https://esphome.io/components/sensor/bme280.html
  - platform: bme280_i2c
    temperature:
      name: Technikraum Temperatur
      id: technikraum_temp
      oversampling: 16x
      on_value:
        then:
          - component.update: technikraum_dewpoint
    humidity:
      name: Technikraum Luftfeuchte
      id: technikraum_hum
      on_value:
        then:
          - component.update: technikraum_dewpoint
    pressure:
      name: Technikraum Luftdruck
    address: 0x76
    update_interval: 60s

  - platform: absolute_humidity
    name: Technikraum Luftfeuchte, absolut
    id: technikraum_hum_abs
    temperature: technikraum_temp
    humidity: technikraum_hum

  - platform: template
    name: Technikraum Taupunkt
    id: technikraum_dewpoint
    unit_of_measurement: °C
    icon: 'mdi:thermometer-alert'
    accuracy_decimals: 1
    lambda: |-
        const float alpha = 6.112;  // hPa
        const float beta = 17.62;
        const float lambda = 243.12;  // °C
        float T = id(technikraum_temp).raw_state;  // Temperature in °C
        float RH = id(technikraum_hum).raw_state;  // Relative Humidity
        float H = log(RH / 100) + beta * T / (lambda + T);
        return lambda * H / (beta - H);
    update_interval: never

  - platform: bme280_i2c
    temperature:
      name: Dachboden Temperatur
      id: dachboden_temp
      oversampling: 16x
      on_value:
        then:
          - component.update: dachboden_dewpoint
    humidity:
      name: Dachboden Luftfeuchte
      id: dachboden_hum
      on_value:
        then:
          - component.update: dachboden_dewpoint
    pressure:
      name: Dachboden Luftdruck
    address: 0x77  # Ungewöhnlicher BME280 mit SDO auf VCC
    update_interval: 60s

  - platform: absolute_humidity
    name: Dachboden Luftfeuchte, absolut
    id: dachboden_hum_abs
    temperature: dachboden_temp
    humidity: dachboden_hum

  - platform: template
    name: Dachboden Taupunkt
    id: dachboden_dewpoint
    unit_of_measurement: °C
    icon: 'mdi:thermometer-alert'
    accuracy_decimals: 1
    lambda: |-
        const float alpha = 6.112;  // hPa
        const float beta = 17.62;
        const float lambda = 243.12;  // °C
        float T = id(dachboden_temp).raw_state;  // Temperature in °C
        float RH = id(dachboden_hum).raw_state;  // Relative Humidity
        float H = log(RH / 100) + beta * T / (lambda + T);
        return lambda * H / (beta - H);
    update_interval: never


binary_sensor:
  - platform: gpio
    name: On-board Button
    id: button_onboard
    pin:
      number: ${on_board_button_pin}
      mode:
        input: True
        pullup: True
      inverted: True
    internal: true
    filters:
      - delayed_on: 300ms
    on_press:
      - button.press: esp_restart_button


switch:
  # Construct an additional GND from GPIO
  - platform: gpio
    internal: true
    restore_mode: ALWAYS_ON
    name: Additional GND Pin 0
    icon: mdi:arrow-collapse-down
    pin:
      number: GPIO0
      inverted: true
      mode:
        output: true
        open_drain: true
