# http://wiki.icbbuy.com/doku.php?id=developmentboard:esp32-c3mini
# https://www.waveshare.com/esp32-c3-zero.htm
# https://www.studiopieters.nl/esp32-c3-pinout/

esphome:
  name: ${device_name}
  friendly_name: ${device_friendly_name}
  area: ${device_area}
  project:
    name: "AWF1877.Raumsensorknoten_ESP32-C3-SuperMini"
    version: "0.1"
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32-c3-devkitm-1
  variant: esp32c3
  framework:
    type: esp-idf

# esp32:
#   board: esp32-c3-devkitm-1
#   variant: esp32c3
#   framework:
#     type: arduino

logger:
  level: DEBUG
#   hardware_uart: USB_SERIAL_JTAG

wifi:
  output_power: 11
