wifi:
  # use_address: 192.168.23.x
  networks:
    - ssid: !secret wifi_home1_ssid
      password: !secret wifi_home1_pw
    - ssid: !secret wifi_home2_ssid
      password: !secret wifi_home2_pw
    - ssid: !secret wifi_home3_ssid
      password: !secret wifi_home3_pw
  ap:
    ssid: "${device_name}"
    password: !secret wifi_fallback_pw
  min_auth_mode: WPA2

sensor:
  # Reports the WiFi signal strength/RSSI in dB
  - platform: wifi_signal
    name: WiFi Signal RSSI
    id: wifi_signal_db
    update_interval: 60s
    device_class: signal_strength
    entity_category: diagnostic

  # Reports the WiFi signal strength in %
  - platform: copy
    source_id: wifi_signal_db
    name: WiFi Signal Strength
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    device_class: ""
    entity_category: diagnostic
