esphome:
  on_boot:
    - priority: -10
      then:
        - servo.detach: servo_motor
        - binary_sensor.template.publish:
            id: sensor_servo_motor_active
            state: OFF
        - sensor.template.publish:
            id: sensor_output_total_g
            state: 0


time:
  - platform: homeassistant
    id: homeassistant_time


globals:
  - id: global_output_target_corrected_g
    type: int
    restore_value: no
    initial_value: '-1.0'

  - id: global_storage_remaining_before_last_run_g
    type: int
    restore_value: no
    initial_value: '0.0'

  - id: global_dt_last_run_start
    type: long int
    restore_value: no

  - id: global_dt_last_run_stop
    type: long int
    restore_value: no


sensor:
  - platform: template
    name: Progress
    id: sensor_output_progress_pct
    icon: mdi:progress-helper
    unit_of_measurement: '%'
    accuracy_decimals: 0

  - platform: template
    name: Last run datetime
    id: sensor_last_run_dt
    icon: mdi:timer-outline
    device_class: timestamp

  - platform: template
    name: Last run duration
    id: sensor_last_run_duration_s
    icon: mdi:timer-cog-outline
    unit_of_measurement: s

  - platform: template
    name: Last run output
    id: sensor_last_run_output_g
    icon: mdi:scale
    device_class: weight
    unit_of_measurement: g
    accuracy_decimals: 0

  - platform: template
    name: Last run speed
    id: sensor_last_run_speed_gps
    icon: mdi:speedometer
    unit_of_measurement: 'g/s'

  - platform: template
    name: Total output
    id: sensor_output_total_g
    icon: mdi:scale
    state_class: total
    device_class: weight
    unit_of_measurement: g
    accuracy_decimals: 0


binary_sensor:
  - platform: template
    name: Dispenser motor active
    id: sensor_servo_motor_active

  - platform: gpio
    name: Case button and on-board button
    internal: true
    pin:
      number: GPIO9
      inverted: true
    filters:
      - delayed_on: 50ms
    on_press:
      then:
        - script.execute:
            id: script_controlled_output
            timeout_sec: 8
            target_g: 9999
            offset_g: 0

#

number:
  - platform: template
    name: Manual motor control
    entity_category: "diagnostic"
    icon: mdi:screw-round-top
    mode: slider
    min_value: 0
    max_value: 100
    initial_value: 0
    step: 1
    optimistic: false
    set_action:
      then:
        - if:
            condition:
              lambda: 'return x > 0;'
            then:
              - servo.write:
                  id: servo_motor
                  level: !lambda 'return x / 100.0;'
            else:
              - servo.detach: servo_motor


button:
  - platform: template
    name: Emergency stop
    on_press:
      - script.stop: script_controlled_output
      - servo.detach: servo_motor
      - light.turn_off: on_board_led
      - binary_sensor.template.publish:
          id: sensor_servo_motor_active
          state: OFF
