substitutions:
  klingel_schwellwert: "2.75"  # V

sensor:
  # https://esphome.io/components/sensor/adc.html

  - platform: adc
    name: "Klingel Messsignal"
    id: klingel_adc_v
    internal: true
    pin: 39
    attenuation: auto
    update_interval: 20ms
    accuracy_decimals: 2
    filters:
      - median:
          window_size: 3
          send_every: 3
      - max:
          window_size: 10
          send_every: 10

  # - platform: adc
  #   name: "Klingel Messsignal roh"
  #   id: adc_klingel_v
  #   internal: true
  #   pin: 39
  #   attenuation: auto
  #   update_interval: 20ms
  #   accuracy_decimals: 2

binary_sensor:
  # https://esphome.io/components/binary_sensor/template.html

  - platform: template
    name: "Klingel"
    icon: mdi:bell-ring
    lambda: |-
      return id(klingel_adc_v).state > float(${klingel_schwellwert});
    filters:
      - delayed_off: 10s
