# Temperatur zu Spannung zu PWM%
# Für 0..10V Modul (EM10) zur Gastherme Temperatursteuerung

output:
  - platform: ledc
    pin: GPIO27
    frequency: 1220 Hz
    id: heiz_sollwert_pwm_output
    inverted: False
    min_power: 0.00
    max_power: 1.00

esphome:
  on_boot:
    - priority: 500
      # When hardware initialized
      # Failsafe temperature, approx. 30°C = 20% PWM
      then:
        - lambda: |-
            id(heiz_sollwert_pwm_output).set_level(0.2);

sensor:
  - platform: template
    name: "Gastherme Sollwert (Temperatur)"
    id: gastherme_sollwert_degc_sensor
    icon: "mdi:thermometer-chevron-up"
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    update_interval: never

  - platform: template
    name: "Gastherme Sollwert (Spannung)"
    id: gastherme_sollwert_volt_sensor
    icon: "mdi:power-plug-outline"
    unit_of_measurement: "V"
    accuracy_decimals: 1
    update_interval: never

  - platform: template
    name: "Gastherme Sollwert (PWM)"
    id: gastherme_sollwert_pwm_sensor
    icon: "mdi:timelapse"
    unit_of_measurement: "%"
    accuracy_decimals: 0
    update_interval: never

api:
  services:
    - service: gastherme_solltemperatur_set  # Wird erweitert um "esphome.heizungsregelung_"
      variables:
        temperature: float
      then:
        - lambda: |-
            double degc = 1.0 * temperature;
            double volt = degc * 0.1253 - 1.2751;
            double pwm_pct = (volt - 0.4535) * 10.05;

            id(gastherme_sollwert_degc_sensor).publish_state(
              min(90.0, max(0.0, degc))
            );
            id(gastherme_sollwert_volt_sensor).publish_state(
              min(10.0, max(0.0, volt))
            );
            id(gastherme_sollwert_pwm_sensor).publish_state(
              min(100.0, max(0.0, pwm_pct))
            );
            id(heiz_sollwert_pwm_output).set_level(
              min(1.0, max(0.0, pwm_pct / 100.0))
            );
