# PWM zu 0..10V Modul (EM10)

# Pin für PWM Ausgabe (Input: 0..1)
output:
  - platform: ledc
    pin: GPIO27
    frequency: 1220 Hz
    id: heiz_sollwert_pwm_output
    inverted: False
    min_power: 0.00
    max_power: 1.00

# Interne Hilfsvariable um den Sollwert in Prozent (0..100 PWM) zu setzen
globals:
  - id: gastherme_sollwert_pwm
    type: int
    #restore_value: yes
    initial_value: '30'  # 0..100

# Sensor um den Sollwert in Prozent (0..100 PMW) rückzuliefert (feedback loop)
sensor:
  - platform: template
    name: "${device_friendly_name} Gastherme Sollwert (PWM level)"
    id: gastherme_sollwert_sensor
    icon: "mdi:pulse"
    unit_of_measurement: "%"
    accuracy_decimals: 0
    update_interval: 60s
    lambda: 'return id(gastherme_sollwert_pwm);'
    on_value:
      then:
        - lambda: |-
            id(gastherme_sollwert_pwm) = x;
            id(heiz_sollwert_pwm_output).set_level(x/100);

# Home Assistant Service um den Sollwert in Prozent (0..100 PWM) vorzugeben
api:
  services:
    - service: gastherme_sollwert_pwm_set  # Wird erweitert um "esphome.heizungsregelung_"
      variables:
        percentage: int
      then:
        - lambda: |-
            id(gastherme_sollwert_sensor).publish_state(percentage);
