sensor:

  - platform: template
    name: "Solarkreis Differenz"
    id: solarkreis_diff
    unit_of_measurement: "K"
    accuracy_decimals: 1
    update_interval: 60s
    lambda: |-
      return (id(sonnenkollektor).state - id(warmwasserspeicher_unten).state);

  - platform: template
    name: "Heizkreis Differenz"
    id: heizkreis_diff
    unit_of_measurement: "K"
    accuracy_decimals: 1
    update_interval: 60s
    lambda: |-
      return (id(heizkreis_vl).state - id(heizkreis_rl).state);

  - platform: template
    name: "Warmwasser Differenz"
    id: warmwasser_diff
    unit_of_measurement: "K"
    accuracy_decimals: 1
    update_interval: 60s
    lambda: |-
      return (id(gastherme_vl).state - id(gastherme_rl_wwb).state);

  - platform: template
    name: "Kessel Differenz"
    id: kessel_diff
    unit_of_measurement: "K"
    accuracy_decimals: 1
    update_interval: 60s
    lambda: |-
      return (id(kessel_vl).state - id(kessel_rl).state);

  - platform: template
    name: "Kesselpufferkreis Differenz"
    id: kesselpufferkreis_diff
    unit_of_measurement: "K"
    accuracy_decimals: 1
    update_interval: 60s
    lambda: |-
      return (id(kesselpufferkreis_vl).state - id(kesselpufferkreis_rl).state);
