# I2C f체r BME280
# https://esphome.io/components/i2c.html
i2c:
  sda: GPIO22
  scl: GPIO21
  scan: true

# SHT3X-D Temperature+Humidity Sensor
# https://esphome.io/components/sensor/sht3xd.html
sensor:
  - platform: sht3xd
    temperature:
      name: "${device_friendly_name} Geh채use Temperatur"
      unit_of_measurement: "째C"
      accuracy_decimals: 1
    humidity:
      name: "${device_friendly_name} Geh채use Luftfeuchte"
      unit_of_measurement: "%"
      accuracy_decimals: 1
    address: 0x44
    update_interval: 60s
