# DS18B20 Temperatursensoren Pin
# https://esphome.io/components/one_wire.html
one_wire:
  - platform: gpio
    id: one_wire_gpio33
    pin: GPIO33

sensor:

  # Pufferspeicher blau: Sensorband DS18B20 Temperatursensoren

  - <<: !include heizungsregelung_temp_ds18b20_template.yaml
    one_wire_id: one_wire_gpio33
    address: 0xa63ce1d4442afd28
    name: Pufferspeicher blau Ladegradsensor 01
    id: puffer_blau_lg_sensor_01
    on_value:
      then:
        - component.update: puffer_blau_ladegrad

  - <<: !include heizungsregelung_temp_ds18b20_template.yaml
    one_wire_id: one_wire_gpio33
    address: 0xe63ce1d444cefa28
    name: Pufferspeicher blau Ladegradsensor 02
    id: puffer_blau_lg_sensor_02

  - <<: !include heizungsregelung_temp_ds18b20_template.yaml
    one_wire_id: one_wire_gpio33
    address: 0x233ce1d4445b7728
    name: Pufferspeicher blau Ladegradsensor 03
    id: puffer_blau_lg_sensor_03

  - <<: !include heizungsregelung_temp_ds18b20_template.yaml
    one_wire_id: one_wire_gpio33
    address: 0xb53ce1d458b4be28
    name: Pufferspeicher blau Ladegradsensor 04
    id: puffer_blau_lg_sensor_04

  - <<: !include heizungsregelung_temp_ds18b20_template.yaml
    one_wire_id: one_wire_gpio33
    address: 0xde3ce1d444097228
    name: Pufferspeicher blau Ladegradsensor 05
    id: puffer_blau_lg_sensor_05

  - <<: !include heizungsregelung_temp_ds18b20_template.yaml
    one_wire_id: one_wire_gpio33
    address: 0x5b3ce1d4440f2328
    name: Pufferspeicher blau Ladegradsensor 06
    id: puffer_blau_lg_sensor_06

  - <<: !include heizungsregelung_temp_ds18b20_template.yaml
    one_wire_id: one_wire_gpio33
    address: 0x283ce1d444ea1a28
    name: Pufferspeicher blau Ladegradsensor 07
    id: puffer_blau_lg_sensor_07

  - <<: !include heizungsregelung_temp_ds18b20_template.yaml
    one_wire_id: one_wire_gpio33
    address: 0x073ce1d4440ca828
    name: Pufferspeicher blau Ladegradsensor 08
    id: puffer_blau_lg_sensor_08

  - <<: !include heizungsregelung_temp_ds18b20_template.yaml
    one_wire_id: one_wire_gpio33
    address: 0x8f3ce1d444961f28
    name: Pufferspeicher blau Ladegradsensor 09
    id: puffer_blau_lg_sensor_09

  - <<: !include heizungsregelung_temp_ds18b20_template.yaml
    one_wire_id: one_wire_gpio33
    address: 0xa33ce1d444932128
    name: Pufferspeicher blau Ladegradsensor 10
    id: puffer_blau_lg_sensor_10

  - <<: !include heizungsregelung_temp_ds18b20_template.yaml
    one_wire_id: one_wire_gpio33
    address: 0x6d3ce1d4446bde28
    name: Pufferspeicher blau Ladegradsensor 11
    id: puffer_blau_lg_sensor_11
    on_value:
      then:
        - component.update: puffer_blau_ladegrad


  # Pufferspeicher blau: Speicherladegrad

  - platform: template
    id: puffer_blau_ladegrad
    name: "Pufferspeicher blau Ladegrad"
    unit_of_measurement: "%"
    icon: "mdi:home-battery-outline"
    accuracy_decimals: 1
    update_interval: never

    lambda: |-
      const float low = 30.0f;

      float raw_high = id(puffer_blau_lg_sensor_11).state;
      if (isnan(raw_high)) return NAN;
      float high = raw_high < 60.0f ? 60.0f : raw_high;

      float span = high - low;
      if (span <= 0.0f) span = 1.0f;

      float vals[11] = {
        id(puffer_blau_lg_sensor_01).state,
        id(puffer_blau_lg_sensor_02).state,
        id(puffer_blau_lg_sensor_03).state,
        id(puffer_blau_lg_sensor_04).state,
        id(puffer_blau_lg_sensor_05).state,
        id(puffer_blau_lg_sensor_06).state,
        id(puffer_blau_lg_sensor_07).state,
        id(puffer_blau_lg_sensor_08).state,
        id(puffer_blau_lg_sensor_09).state,
        id(puffer_blau_lg_sensor_10).state,
        id(puffer_blau_lg_sensor_11).state
      };

      for (int i = 0; i < 11; i++) {
        if (isnan(vals[i])) return NAN;
      }

      float total_pct = 0.0f;
      for (int i = 0; i < 11; i++) {
        float v = vals[i];
        float pct;
        if (v <= low) pct = 0.0f;
        else if (v >= high) pct = 100.0f;
        else pct = (v - low) / span * 100.0f;
        total_pct += pct;
      }

      float mean_pct = total_pct / 11.0f;
      return roundf(mean_pct * 10.0f) / 10.0f;