sensor:
  - platform: pulse_meter
    name: "${device_friendly_name} Pulse Meter 39 Leistung"
    pin: GPIO39
    internal_filter: 50ms
    accuracy_decimals: 3
    timeout:
      minutes: 5
    internal_filter_mode: EDGE
