
light:
  - platform: esp32_rmt_led_strip
    id: on_board_led
    name: On-Board Status LED
    icon: "mdi:alarm-light"
    pin: ${status_led_pin}
    rgb_order: GRB
    num_leds: 1
    rmt_channel: 0
    chipset: SK6812
    restore_mode: ALWAYS_OFF

esphome:
  on_boot:
    - priority: 600
      then:
        - light.turn_on:
            id: on_board_led
            red: 0%
            green: 0%
            blue: 100%
            brightness: 10%
            transition_length: 0ms
        - delay: 500ms
        - light.turn_on:
            id: on_board_led
            red: 0%
            green: 0%
            blue: 100%
            brightness: 100%
            transition_length: 1500ms
    - priority: 240
      then:
        - light.turn_on:
            id: on_board_led
            red: 0%
            green: 100%
            blue: 100%
            brightness: 10%
            transition_length: 500ms
    - priority: 200
      then:
        - light.turn_on:
            id: on_board_led
            red: 0%
            green: 100%
            blue: 0%
            brightness: 10%
            transition_length: 500ms
        - delay: 500ms
        - light.turn_off:
            id: on_board_led
            transition_length: 500ms
