light:
  - platform: status_led
    id: on_board_led
    name: On-Board Status LED
    icon: "mdi:alarm-light"
    pin:
      number: ${status_led_pin}
      inverted: true
    restore_mode: ALWAYS_OFF

esphome:
  on_boot:
    - priority: 600
      then:
        - light.turn_on:
            id: on_board_led
            brightness: 100%
            transition_length: 1500ms
    - priority: 200
      then:
        - light.turn_on:
            id: on_board_led
            brightness: 20%
            transition_length: 500ms
        - delay: 500ms
        - light.turn_off:
            id: on_board_led
            transition_length: 500ms
